### ISSUE TITLE
Snappy FAQ Uploader

### ISSUE THREAD

**Issue by imsickofmaps** [praekelt/django-refugeerights#11]
- [x] New snappyuploader django app
- [x] Add model for failed file contents 
- [x] Add model for Snappy FAQs
- [x] Add Celery task for syncing FAQ's
- [x] Override admin list view with button for uploader
- [x] Uploader select file page with FAQ list drop down
- [x] CSV format `lang, topic, question, answer`
- [x] File handler uses CSV Dict to get data, dump exceptions to db field
- [x] Celery task for uploading, should accept dict
- [x] FAQs should be created `[lang] question` with `answer` applied to `[lang] topic`

**Comment by gsvr** [comment]
This issue was broken into #12 #13 #14
